spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret-dev
      prod: prod-server, common, secret-prod
      keun: keun-server, common, secret-prod
      hyeokjun: hyeokjun-server, common, secret-prod
      minseok: minseok-server, common, secret-prod
      hyeonjung: hyeonjung-server, common, secret-prod

--- 
spring:
  config:
    activate:
      on-profile: dev

domain:
  name:
    http: http://localhost:8080
    https: https://localhost:8080

app:
  cors:
    allowed-origins: http://localhost:5173,http://localhost:3000

---
spring:
  config:
    activate:
      on-profile: keun-server

domain:
  name:
    http: http://oxoxox.store
    https: https://oxoxox.store

app:
  cors:
    allowed-origins: https://oxoxox.store

---
spring:
  config:
    activate:
      on-profile: hyeokjun-server

domain:
  name:
    http: http://kakakao.store
    https: https://kakakao.store

app:
  cors:
    allowed-origins: https://kakakao.store

---
spring:
  config:
    activate:
      on-profile: minseok-server

domain:
  name:
    http: http://fridgemate.store
    https: https://fridgemate.store

app:
  cors:
    allowed-origins: https://fridgemate.store

---
spring:
  config:
    activate:
      on-profile: hyeonjung-server

domain:
  name:
    http: http://xoxoxo.store
    https: https://xoxoxo.store

app:
  cors:
    allowed-origins: https://xoxoxo.store

---

spring:
  config:
    activate:
      on-profile: common

  application:
    name: team-ljco-fridgemate

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 2MB

file:
  upload-dir: ./uploads/images
  base-url: ${domain.name.http}

server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

springdoc:
  swagger-ui:
    path: /doc
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs

mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  type-aliases-package: com.korit.team_ljco.entity

logging:
  level:
    com.korit.team_ljco: ${LOG_LEVEL:DEBUG}
    org.springframework.security: ${LOG_LEVEL:DEBUG}
    org.mybatis: ${LOG_LEVEL:DEBUG}
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
