spring:
  profiles:
    active: dev
    group:
      dev: dev, common, secret-dev
      keun: keun-server, common, secret-prod
      hyeokjun: hyeokjun-server, common, secret-prod
      minseok: minseok-server, common, secret-prod
      hyeonjung: hyeonjung-server, common, secret-prod

---
spring:
  config:
    activate:
      on-profile: dev

domain:
  name:
    http: http://localhost:8080
    https: https://localgost:8080

---
spring:
  config:
    activate:
      on-profile: keun-server

domain:
  name:
    http: http://oxoxox.store
    https: http://oxoxox.store

---

spring:
  config:
    activate:
      on-profile: hyeokjun-server

domain:
  name:
    http: http://kakakao.store
    https: http://kakakao.store

---

spring:
  config:
    activate:
      on-profile: hyeonjung-server

domain:
  name:
    http: http://oxoxox.store
    https: http://oxoxox.store
---

spring:
  config:
    activate:
      on-profile: minseok-server

domain:
  name:
    http: http://oxoxox.store
    https: http://oxoxox.store

---


spring:
  config:
    activate:
      on-profile: common

  application:
    name: team-ljco-fridgemate

  # 파일 업로드 설정
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB
      file-size-threshold: 2MB

file:
  upload-dir: ./uploads/images
  base-url: http://localhost:8080





# 서버 설정
server:
  port: 8080
  tomcat:
    max-swallow-size: -1
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

# Swagger 설정 (API 문서)
springdoc:
  swagger-ui:
    path: /doc
    operations-sorter: alpha
    tags-sorter: alpha
  api-docs:
    path: /api-docs

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true   # user_id -> userId 자동 변환
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl  # SQL 로그
  type-aliases-package: com.korit.team_ljco.entity

# 로깅 설정
logging:
  level:
    com.korit.team_ljco: DEBUG
    org.springframework.security: DEBUG
    org.mybatis: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"